name: sync a fork
on:
    repository_dispatch:
        types: run-sync
    schedule:
        - cron: "30 * * * *"

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: sync phpmyadmin fork
              uses: sudo-bot/action-fork-sync@v1.0.4
              with:
                  source-url: "https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/phpmyadmin/phpmyadmin.git"
                  fork-url: "https://${{ secrets.BOT_TOKEN }}:x-oauth-basic@github.com/williamdes/phpmyadmintest.git"
                  clone-depth: "100"
                  branches: "master,QA_5_0,QA_4_9,STABLE"
